var STATE;
(function (STATE) {
    STATE[STATE["MAIN"] = 0] = "MAIN";
    STATE[STATE["MATCHIMG"] = 1] = "MATCHIMG";
    STATE[STATE["FIGHT_BEGIN"] = 2] = "FIGHT_BEGIN";
    STATE[STATE["FIGHT_OVER"] = 3] = "FIGHT_OVER";
})(STATE || (STATE = {}));
